#ifndef __KL2EDK_AUTOGEN_global_functions__
#define __KL2EDK_AUTOGEN_global_functions__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'global_functions.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.2
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"


#endif // __KL2EDK_AUTOGEN_global_functions__
