#ifndef __KL2EDK_AUTOGEN_MkCIFAR_type__
#define __KL2EDK_AUTOGEN_MkCIFAR_type__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'MkCIFAR_type.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.2
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL object 'MkCIFAR'
// Defined at MkCIFAR.kl:12:1

class MkCIFAR
{
protected:
  
  struct Bits;
  Bits *m_bits;
  
  friend struct Traits< MkCIFAR >;
  
  static void ConstructEmpty( MkCIFAR *self );
  
  static void ConstructCopy( MkCIFAR *self, MkCIFAR const *other );
  
  static void AssignCopy( MkCIFAR *self, MkCIFAR const *other );
  
  static void Destruct( MkCIFAR *self );
  
public: 
  
  typedef MkCIFAR &Result;
  typedef MkCIFAR const &INParam;
  typedef MkCIFAR &IOParam;
  
  MkCIFAR();
  
  static MkCIFAR Create();
  
  MkCIFAR( MkCIFAR const &that );
  
  MkCIFAR &operator =( MkCIFAR const &that );
  
  ~MkCIFAR();
  
  void appendDesc( String::IOParam string ) const;
  uint32_t getRefCount() const;
  Type getType() const;
  
  bool isValid() const;
  
  operator bool() const;
  
  bool operator !() const;
  
  Bits *operator ->();
  
  Bits const *operator ->() const;
  
  bool operator ==( INParam that );
  
  bool operator !=( INParam that );
  
  // Methods for 'Object'
};

inline void Traits<MkCIFAR>::ConstructEmpty( MkCIFAR &val )
{
  MkCIFAR::ConstructEmpty( &val );
}
inline void Traits<MkCIFAR>::ConstructCopy( MkCIFAR &lhs, MkCIFAR const &rhs )
{
  MkCIFAR::ConstructCopy( &lhs, &rhs );
}
inline void Traits<MkCIFAR>::AssignCopy( MkCIFAR &lhs, MkCIFAR const &rhs )
{
  MkCIFAR::AssignCopy( &lhs, &rhs );
}
inline void Traits<MkCIFAR>::Destruct( MkCIFAR &val )
{
  MkCIFAR::Destruct( &val );
}

}}}

#endif // __KL2EDK_AUTOGEN_MkCIFAR_type__
