#ifndef __KL2EDK_AUTOGEN_MkCIFAR_functions__
#define __KL2EDK_AUTOGEN_MkCIFAR_functions__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'MkCIFAR_functions.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.2
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "MkCIFAR_type.h"


// Defined at MkCIFAR.kl:16:1
FABRIC_EXT_EXPORT void MkCIFAR_parseBatch(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::MkCIFAR >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam path,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float64 > > >::IOParam images,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt32 > >::IOParam labels
);

#endif // __KL2EDK_AUTOGEN_MkCIFAR_functions__
