#ifndef __KL2EDK_AUTOGEN_global_functions__
#define __KL2EDK_AUTOGEN_global_functions__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'global_functions.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.2
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"


// Defined at MkMNIST.kl:27:1
FABRIC_EXT_EXPORT void UniformRand_Float64(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam min,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam max,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::IOParam res
);

// Defined at MkMNIST.kl:30:1
FABRIC_EXT_EXPORT void UniformRand_Float32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam min,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam max,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::IOParam res
);

// Defined at MkMNIST.kl:33:1
FABRIC_EXT_EXPORT void UniformRand_SInt32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam min,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam max,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::IOParam res
);

// Defined at MkMNIST.kl:36:1
FABRIC_EXT_EXPORT void UniformRand_UInt32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam min,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam max,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::IOParam res
);

// Defined at MkMNIST.kl:40:1
FABRIC_EXT_EXPORT void UniformRealDistribution_Float64(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam min,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam max,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float64 > >::IOParam dist
);

// Defined at MkMNIST.kl:43:1
FABRIC_EXT_EXPORT void UniformRealDistribution_Float32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam min,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam max,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float32 > >::IOParam dist
);

// Defined at MkMNIST.kl:46:1
FABRIC_EXT_EXPORT void UniformRealDistribution_UInt32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam min,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::INParam max,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt32 > >::IOParam dist
);

// Defined at MkMNIST.kl:49:1
FABRIC_EXT_EXPORT void UniformRealDistribution_SInt32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam min,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::SInt32 >::INParam max,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::SInt32 > >::IOParam dist
);

// Defined at MkMNIST.kl:52:1
FABRIC_EXT_EXPORT void Bernoulli_Float64(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam p,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::IOParam res
);

// Defined at MkMNIST.kl:55:1
FABRIC_EXT_EXPORT void Bernoulli_Float32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam p,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Boolean >::IOParam res
);

// Defined at MkMNIST.kl:58:1
FABRIC_EXT_EXPORT void Bernoulli_Float64_UInt32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam p,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::IOParam res
);

// Defined at MkMNIST.kl:61:1
FABRIC_EXT_EXPORT void Bernoulli_Float32_UInt32(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float32 >::INParam p,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::UInt32 >::IOParam res
);

#endif // __KL2EDK_AUTOGEN_global_functions__
