#ifndef __KL2EDK_AUTOGEN_MkMNIST__
#define __KL2EDK_AUTOGEN_MkMNIST__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'MkMNIST.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.2
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

#include "MkMNIST_functions.h"
#include "MkMNIST_impl.h"
#include "MkMNIST_type.h"
#include "global_functions.h"

#endif // __KL2EDK_AUTOGEN_MkMNIST__
