#ifndef __KL2EDK_AUTOGEN_MkMNIST_functions__
#define __KL2EDK_AUTOGEN_MkMNIST_functions__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'MkMNIST_functions.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.2
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "MkMNIST_type.h"


// Defined at MkMNIST.kl:16:1
FABRIC_EXT_EXPORT void MkMNIST_parseLabels(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::UInt32 > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::MkMNIST >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam path
);

// Defined at MkMNIST.kl:19:1
FABRIC_EXT_EXPORT void MkMNIST_parseImages(
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::VariableArray< Fabric::EDK::KL::Float64 > > >::Result _result,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::MkMNIST >::INParam this_,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::String >::INParam path,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam scale_min,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam scale_max,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam x_padding,
  Fabric::EDK::KL::Traits< Fabric::EDK::KL::Float64 >::INParam y_padding
);

#endif // __KL2EDK_AUTOGEN_MkMNIST_functions__
