####################################################################################################
#                                                                                                  #
#   Informations :                                                                                 #
#       This code is part of the project Medical                                                   #
#                                                                                                  #
#   Contacts :                                                                                     #
#       couet.julien@gmail.com                                                                     #
#                                                                                                  #
####################################################################################################

import os, re, sys, subprocess
from sys import platform as _platform


try:
  fabricEDKPath = os.environ['FABRIC_DIR']
except:
  print "You must set FABRIC_DIR in your environment."
  print "Refer to README.txt for more information."
  sys.exit(1)
SConscript(os.path.join(fabricEDKPath, 'Samples', 'EDK', 'SConscript'))
Import('fabricBuildEnv')
 
# Use of this flags to have access to C++11 
flags = {
  'CPPPATH': ['C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include'],
  'LIBPATH': []
}
#flags['LINKFLAGS'] = [
# '-stdlib=libc++']
flags['CPPFLAGS'] = ['/O2']

#C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include

fabricBuildEnv.MergeFlags(flags)
fabricBuildEnv.Extension(
  'MkMNIST', 
  [ 
    'MkMNIST.cpp', 'MkMNIST.kl'
  ])


 