
set FABRIC_DIR=C:\Program Files\FabricEngine-1.15.2-Windows-x86_64

set PATH=%FABRIC_DIR%\bin;%PATH%

set _OLD_PYTHON_VERSION=%PYTHON_VERSION%
set PYTHON_VERSION=2.7
set PYTHONPATH=%FABRIC_DIR%\Python\%PYTHON_VERSION%;%PYTHONPATH%
set PYTHON_VERSION=%_OLD_PYTHON_VERSION%

set FABRIC_EXTS_PATH=%FABRIC_DIR%\Exts
set KLML_EXTS_CPP_MNIST_PATH=C:\Users\Julien\Documents\Dev\MLKL\core\c++\MNIST
set KLML_EXTS_PATH=C:\Users\Julien\Documents\Dev\MLKL\core\kl

set KLML_EXTS_CPP_PATH=%KLML_EXTS_CPP_MNIST_PATH%
set FABRIC_EXTS_PATH=%KLML_EXTS_CPP_PATH%;%KLML_EXTS_PATH%;%FABRIC_EXTS_PATH%

