
set FABRIC_DIR=C:\Program Files\FabricEngine-1.15.2-Windows-x86_64

set PATH=%FABRIC_DIR%\bin;%PATH%

set _OLD_PYTHON_VERSION=%PYTHON_VERSION%
set PYTHON_VERSION=2.7
set PYTHONPATH=%FABRIC_DIR%\Python\%PYTHON_VERSION%;%PYTHONPATH%
set PYTHON_VERSION=%_OLD_PYTHON_VERSION%

set MLKL_CPP_EXTS=C:\Users\Julien\Documents\Dev\MLKL\core\c++\MNIST
set MLKL_EXTS=C:\Users\Julien\Documents\Dev\MLKL\core\kl
 
set FABRIC_EXTS_PATH=%FABRIC_DIR%\Exts
set FABRIC_EXTS_PATH=%MLKL_CPP_EXTS%;%MLKL_EXTS%;%FABRIC_EXTS_PATH%

